#!/usr/bin/env python3
"""
Copy daily_football_data/sims/ → sportintel repo data/sims/ and push.

Requires:
  GITHUB_TOKEN or GH_TOKEN with repo scope on the target admin repo
  Optional: SPORTINTEL_REPO (default avramnull/sportintel)
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from si_config import SIMS_DIR, SPORTINTEL_REPO, GITHUB_TOKEN  # noqa: E402
from si_logging import get_logger  # noqa: E402

log = get_logger("publish")


def run(cmd, cwd=None):
    log.info("exec: %s", " ".join(cmd))
    subprocess.check_call(cmd, cwd=cwd)


def main():
    if not SIMS_DIR.exists() or not (SIMS_DIR / "index.json").exists():
        raise SystemExit(f"No sims index at {SIMS_DIR}/index.json")
    if not GITHUB_TOKEN:
        raise SystemExit(
            "Set GITHUB_TOKEN (or GH_TOKEN / SPORTINTEL_TOKEN / SPORTINTEL_PUSH_TOKEN) "
            "to push admin sims"
        )

    # Never echo the token
    url = f"https://x-access-token:{GITHUB_TOKEN}@github.com/{SPORTINTEL_REPO}.git"
    with tempfile.TemporaryDirectory(prefix="sportintel-") as tmp:
        tmp = Path(tmp)
        run(["git", "clone", "--depth", "1", url, str(tmp / "repo")])
        repo = tmp / "repo"
        dest = repo / "data" / "sims"
        # Preserve history of index only; replace report files atomically
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(SIMS_DIR, dest)
        readme = dest / "README.md"
        if not readme.exists():
            readme.write_text(
                "# Fixture simulation lab\n\n"
                "Daily `sim.py` reports for Control Room → Sim Lab.\n"
                "Generated by sportintel_core daily pipeline.\n",
                encoding="utf-8",
            )
        run(["git", "config", "user.email", "github-actions[bot]@users.noreply.github.com"], cwd=repo)
        run(["git", "config", "user.name", "github-actions[bot]"], cwd=repo)
        run(["git", "add", "data/sims"], cwd=repo)
        st = subprocess.run(["git", "diff", "--staged", "--quiet"], cwd=repo)
        if st.returncode == 0:
            log.info("No sim changes to publish")
            return
        msg = f"Sim Lab daily reports: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}"
        run(["git", "commit", "-m", msg], cwd=repo)
        run(["git", "push", "origin", "HEAD"], cwd=repo)
        log.info("Published sims → https://github.com/%s/tree/main/data/sims", SPORTINTEL_REPO)


if __name__ == "__main__":
    main()
